### ISSUE TITLE
Model->find() crashes on conditions

### ISSUE THREAD

**Issue by ipundit** [php-activerecord/activerecord#37]
In Model.php:

/*
 * array<"conditions", array<string,string>>
*/
public static function find(/* $type, $options */)

crashes with this test case:

In ActiveRecordFindTest.php:

    public function test_find_by_conditions()
    {
        $author = Author::find(['conditions'=>["author_id = (?)", 3]]);
        $this->assertEquals(3, $author->id);
    }

because 0 options after extracting ['conditions'] is treated as multiple rows when it should be treated as a single row.

**Comment by shmax** [comment]
I'm not sure what you mean about extracting conditions, but I think this behavior is expected; it returns an array regardless of how many results you get back so that your client code doesn't have to do a lot of checking for number of items; it can assume array.

**Comment by shmax** [comment]
On a related note, I did change some of the logic around single vs plural returns in `Model::find` a few years ago, but didn't touch the tests. So, let me add a few TODO items for this weekend:

* [ ] write tests to fully exercise the return table [here] https://github.com/php-activerecord/activerecord/blob/master/lib/Model.php#L1717
* [ ] write a PHPStan reflection to model those rules (I have some code in my private code base for this)

Please let me know if you're interested in either project, otherwise I'll plan on tackling them myself

**Comment by shmax** [comment]
I've formalized the rules in a PHPStan extension, and as far as I can tell everything is working as expected. I'll close this now, but feel free to reopen if something still feels a bit off.
